(async ()=> {
    try {
        console.log("Hello World");
    } catch (err) {
        console.log("Error: ", err)
    }
})();